account/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView

from libs.djcontrib.conf.urls import decorated_patterns
from libs.djcontrib.utils.decorators import combo
from libs.djcontrib.views.generic import FlashRedirectView
from libs.permitter.decorators import check_perm
from libs.djcontrib.utils.decorators import obj_by_pk

from otakantaa.decorators import legacy_json_plaintext

from . import views
from .models import User
from .perms import CanEditUser, CanViewUserProfile


urlpatterns = [
    url(r'^rekisteroidy/$', views.SignupView.as_view(), name='signup'),
    url(r'^valitse-rekisteroitymistapa/$', views.SignupChoicesView.as_view(),
        name='signup_choices'),
    url(r'^rekisteroidy/facebook/$', views.SignupView.as_view(facebook=True),
        name='signup_facebook'),
    url(r'^kirjaudu-sisaan/$', views.LoginView.as_view(), name='login'),
    url(r'^kirjaudu-ulos/$', views.LogoutView.as_view(), name='logout'),
    url(r'^aktivoi/$', TemplateView.as_view(
        template_name="account/authentication/signup_activation.html"
    ), name='activate'),
    url(r'^vahvista-sahkoposti/(?P<token>\w{26,50})/$',
        views.EmailConfirmationView.as_view(), name='confirm_email'),
    url(r'^(?P<user_id>\d+)/$',
        obj_by_pk(User, 'user_id')(check_perm(CanViewUserProfile)(
            views.UserProfileView.as_view())), name='profile'),
    url(r'(?P<user_id>\d+)/lista/$', views.UserProfileSchemeListView.as_view(),
        name='scheme_list'),
    url(r'^nollaa-salasana/$', auth.password_reset, name='reset_password',
        kwargs={
            'template_name': 'account/authentication/user_reset_password.html',
            'email_template_name': 'account/email/password_reset.txt',
            'subject_template_name': 'account/email/password_reset_title.txt',
            'post_reset_redirect': 'account:password_reset_done',
        }),
    url(r'^nollaa-salasana/linkki-lahetetty/$', auth.password_reset_done,
        name='password_reset_done',
        kwargs={'template_name':
                'account/authentication/user_reset_password_link_sent.html'}),
    url(r'^nollaa-salasana/vahvista/(?P<uidb64>[0-9A-Za-z_\-]+)'
        '/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.password_reset_confirm,
        name='password_reset_confirm',
        kwargs={
            'template_name': 'account/authentication/user_reset_password_confirm.html',
            'post_reset_redirect': 'account:password_reset_ready'
        }),
    url(r'^nollaa-salasana/valmis/$',
        FlashRedirectView.as_view(
            message=_("Salasanasi on vaihdettu. Voit nyt kirjautua sisään "
                      "käyttäen uutta salasanaasi."),
            pattern_name='account:login',
            permanent=True
        ), name='password_reset_ready')
]

urlpatterns += decorated_patterns(
    '',
    combo(obj_by_pk(User, 'user_id'), check_perm(CanEditUser)),
    url(r'(?P<user_id>\d+)/asetukset/$', views.UserSettingsView.as_view(),
        name='settings'),
    url(r'(?P<user_id>\d+)/nayta-asetukset/',
        views.UserSettingsDetailView.as_view(),
        name='settings_detail'),
    url(r'(?P<user_id>\d+)/muokkaa-asetukset/',
        views.UserSettingsEditView.as_view(),
        name='settings_edit'),
    url(r'(?P<user_id>\d+)/asetukset/kuva/$', views.ProfilePictureView.as_view(),
        name='profile_picture'),
    url(r'(?P<user_id>\d+)/asetukset/kuva/muokkaa/$',
        legacy_json_plaintext(views.EditProfilePictureView.as_view()),
        name='edit_profile_picture'),
    url(r'(?P<user_id>\d+)/asetukset/kuva/poista/$',
        views.DeleteProfilePictureView.as_view(),
        name='delete_profile_picture'),
    url(r'(?P<user_id>\d+)/sulje/$',
        views.CloseAccountView.as_view(logout=True),
        name='close'),
    url(r'^(?P<user_id>\d+)/salasanan-vaihto/$', views.UserChangePasswordView.as_view(),
        name='password'),
    url(r'^(?P<user_id>\d+)/viestit/$',
        views.MessagesListView.as_view(),
        name="messages"),
    url(r'^(?P<user_id>\d+)/viestit/(?P<message_id>\d+)/$',
        views.MessageDetailView.as_view(),
        name="show_message"),
    url(r'^(?P<user_id>\d+)/viestit/(?P<message_id>\d+)/#(?P<anchor>[-_\w]+)$',
        views.MessageDetailView.as_view(),
        name="show_message"),
    url(r'^(?P<user_id>\d+)/viestit/(?P<message_id>\d+)/vastaa/$',
        views.CreateMessageView.as_view(),
        name="respond_message"),
    url(r'^(?P<user_id>\d+)/viestit/uusi/$',
        views.CreateMessageView.as_view(),
        name="create_message"),
    url(r'^(?P<user_id>\d+)/viestit/uusi/(?P<scheme_id>\d+)/$',
        views.CreateMessageView.as_view(),
        name="create_message"),
    url(r'^(?P<user_id>\d+)/viestit/taulu/$',
        views.MessagesListView.as_view(template_name="account/messages/list_table.html"),
        name="messages_table"),
    url(r'^(?P<user_id>\d+)/viestit/(?P<message_id>\d+)/poista/$',
        views.DeleteMessageView.as_view(),
        name="delete_message"),
    url(r'(?P<user_id>\d+)/muokkaa-ilmoitukset/$',
        views.NotificationOptionsEditView.as_view(),
        name='notification_options_edit'),
    url(r'(?P<user_id>\d+)/nayta-ilmoitukset/$',
        views.NotificationOptionsDetailView.as_view(),
        name='notification_options_detail'),
)

content/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import url, include

from libs.djcontrib.conf.urls import decorated_patterns
from libs.djcontrib.utils.decorators import obj_by_pk, combo
from libs.permitter.decorators import check_perm

from otakantaa.decorators import legacy_json_plaintext
from otakantaa.perms import IsAuthenticated

from . import views, forms
from .perms import CanPublishScheme, CanRevertSchemeToDraft, CanAcceptInvitation, \
    CanCloseScheme, CanReopenScheme, CanDeleteScheme, CanViewScheme, CanEditScheme, \
    CanExportSchemePdf, CanExportSchemeExcel, CanExportSchemeWord
from .models import Scheme

scheme_as_obj = obj_by_pk(Scheme, 'scheme_id')
interaction_choices = [str(k) for k, v in Scheme.INTERACTION_CHOICES]

SCHEME_FRAGMENT_URLS = (
    # (url part, template name/url name part, form_class, view_class)
    (r'kuva',           'picture',          forms.EditSchemePictureForm),
    (r'otsikko',        'title',            forms.EditSchemeTitleForm),
    (r'kuvaus',         'description',      forms.EditSchemeDescriptionForm),
    (r'ingressi',       'lead_text',        forms.EditSchemeLeadTextForm),
    (r'yhteenveto',     'summary',          forms.EditSchemeSummaryForm),
    (r'omistajat',      'owners',           None, views.SchemeOwnersEditView),
    (r'aiheet',         'tags',             forms.EditSchemeTagsForm),
    (r'kunnat',         'municipalities',   forms.EditSchemeMunicipalitiesForm),
)

partial_detail_urls = [
    url(r'hankkeet/(?P<scheme_id>\d+)/nayta/%s/$' % u[0],
        views.ContentPartialDetailView.as_view(),
        name='scheme_detail_%s' % u[1],
        kwargs={'template_name': 'content/parts/scheme_detail_%s.html' % u[1]})
    for u in SCHEME_FRAGMENT_URLS
]

partial_edit_patterns = [
    url(r'hankkeet/(?P<scheme_id>\d+)/muokkaa/%s/$' % u[0],
        legacy_json_plaintext((u[3] if len(u) > 3 else
        views.SchemePartialEditView).as_view()), name='edit_scheme_%s' % u[1],
        kwargs={'template_name': 'content/parts/scheme_edit_%s_form.html' % u[1],
                'form_class': u[2], 'fragment': u[1]})
    for u in SCHEME_FRAGMENT_URLS
]

urlpatterns = [
    url(r'hankkeet/uusi/$', check_perm(IsAuthenticated)(views.CreateSchemeView.as_view()),
        name='create_scheme'),
    url(r'hankkeet/(?P<scheme_id>\d+)/julkaise/$',
        scheme_as_obj(check_perm(CanPublishScheme)(views.PublishSchemeView.as_view())),
        name='publish_scheme'),
    url(r'hankkeet/(?P<scheme_id>\d+)/poista/$',
        scheme_as_obj(check_perm(CanDeleteScheme)(views.DeleteSchemeView.as_view())),
        name='delete_scheme'),
    url(r'hankkeet/(?P<scheme_id>\d+)/julkaiseminen/$',
        scheme_as_obj(check_perm(CanPublishScheme)(
            views.TryPublishSchemeView.as_view())), name='try_publish'),
    url(r'hankkeet/(?P<scheme_id>\d+)/paattaminen/$',
        scheme_as_obj(check_perm(CanCloseScheme)(
            views.TryCloseSchemeView.as_view())), name='try_close'),
    url(r'hankkeet/(?P<scheme_id>\d+)/avaa/$',
        scheme_as_obj(check_perm(CanReopenScheme)(views.ReOpenSchemeView.as_view())),
        name='reopen_scheme'),
    url(r'hankkeet/(?P<scheme_id>\d+)/muuta-luonnokseksi/$',
        scheme_as_obj(check_perm(CanRevertSchemeToDraft)(
            views.RevertSchemeToDraftView.as_view())), name='revert_scheme_to_draft'),
    url(r'hankkeet/(?P<scheme_id>\d+)/vahvista-kutsu/(?P<scheme_owner_id>\d+)/',
        scheme_as_obj(check_perm(CanAcceptInvitation)(
            views.SchemeOwnerInvitationView.as_view())), name="owner_invitation"),
    url(r'hankkeet/(?P<scheme_id>\d+)/aseta-osallistujat/(?P<interaction>[' +
        ",".join(interaction_choices) + '])/$',
        scheme_as_obj(check_perm(CanEditScheme)(views.SetInteractionView.as_view())),
        name='scheme_set_interaction'),
    url(r'^rss/$', views.SchemeFeed(), name='rss'),
    url(r'^hankkeet/lataa-lisaa/$', views.LoadSchemesView.as_view(),
        name='load_schemes'),

    # Export.
    url(r'hankkeet/(?P<scheme_id>\d+)/pdf/',
        scheme_as_obj(check_perm(CanExportSchemePdf)(
            views.SchemePdfExportView.as_view()
        )), name="scheme_pdf_export"),
    url(r'hankkeet/(?P<scheme_id>\d+)/excel/',
        scheme_as_obj(check_perm(CanExportSchemeExcel)(
            views.ParticipationExcelExportView.as_view()
        )), name="participation_excel_export"),
    url(r'hankkeet/(?P<scheme_id>\d+)/word/',
        scheme_as_obj(check_perm(CanExportSchemeWord)(
            views.SchemeWordExportView.as_view()
        )), name="participation_word_export"),
]

urlpatterns += decorated_patterns('', scheme_as_obj,
    url(r'hankkeet/(?P<scheme_id>\d+)/osallistuminen/',
        include('content.urls_participation', namespace='participation')),
)

urlpatterns += decorated_patterns('', combo(scheme_as_obj, check_perm(CanViewScheme)),
    url(r'^hankkeet/(?P<scheme_id>\d+)/$', views.SchemeDetailView.as_view(),
        name='scheme_detail'),
    url(r'hankkeet/(?P<scheme_id>\d+)/liitteet/nayta/$', views.AttachmentsDetailView.
        as_view(), name='attachment_list'),
    *partial_detail_urls
)

urlpatterns += decorated_patterns('', combo(scheme_as_obj, check_perm(CanEditScheme)),
    url(r'hankkeet/(?P<scheme_id>\d+)/poista/kuva/$',
        views.DeleteSchemePictureView.as_view(), name='delete_scheme_picture'),
    url(r'hankkeet/(?P<scheme_id>\d+)/liitteet/muokkaa/$',
        views.UploadMultipleAttachmentsSchemeView.as_view(), name='add_attachments'),
    url(r'hankkeet/(?P<scheme_id>\d+)/liitteet/(?P<upload_id>\d+)/poista/$',
        views.DeleteAttachmentView.as_view(), name='delete_attachment'),
    url(r'hankkeet/(?P<scheme_id>\d+)/esimoderointi/(?P<premoderation_state>(0|1))/$',
        views.PremoderationToggleView.as_view(), name='toggle_premoderation'),
    url(r'^hankkeet/(?P<scheme_id>\d+)/twitter-hakusana/$',
        views.SchemeTwitterSearchFormView.as_view(), name="twitter_search"),
    *partial_edit_patterns
)

help/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views
from .models import Instruction

link_slug_pattern = '{0}|{1}'.format(Instruction.TYPE_PRIVACY_POLICY,
                                     Instruction.TYPE_CONTACT_DETAILS)

urlpatterns = [
    url(r'^$', views.InstructionDetailFirst.as_view(permanent=True), name='instruction_list'),
    url(r'(?P<pk>\d+)/$', views.InstructionDetail.as_view(), name='instruction_detail'),
    url(r'^linkki/(?P<slug>%s)/$' % link_slug_pattern,
        views.LinkedInstructionRedirectView.as_view(permanent=True),
        name='linked_instruction_redirect'),
]

libs/attachtor/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url('^(?P<upload_group_id>[a-f0-9]{32})(?P<upload_token>[a-f0-9]{32})/$',
        views.UploadAttachmentView.as_view(),
        name='attachtor_file_upload')
)

okwidget/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^hankkeet/$', views.SchemeListWidgetView.as_view(),
        name="scheme_list"),
    url(r'^hankkeet/modal/$', views.SchemeListWidgetModalView.as_view(),
        name="scheme_list_modal"),
    url(r'^hankkeet/(?P<scheme_id>\d+)/$',
        views.SchemeWidgetView.as_view(), name="scheme"),
    url(r'^hankkeet/(?P<scheme_id>\d+)/modal/$',
        views.SchemeWidgetModalView.as_view(), name="scheme_modal"),
]

otakantaa/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic.base import RedirectView

from content.views import UploadAttachmentView, SchemesView

from libs.djcontrib.utils.decorators import combo
from libs.permitter.decorators import check_perm
from libs.moderation.helpers import auto_discover

from okmessages.views import FeedbackView

from .views import AllowedFileUploadExtensions, error_page_not_found
from .decorators import legacy_json_plaintext
from .perms import IsAuthenticated


auto_discover()

urlpatterns = [
    url('^api/$', RedirectView.as_view(url='/api/open/0.1/', permanent=False)),  # HACK
    url(r'^api/open/', include('openapi.urls', namespace='openapi')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', SchemesView.as_view(), name='schemes'),
    url(r'^kayttaja/', include('account.urls', namespace='account')),
    url(r'^', include('content.urls', namespace='content')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^hallinta/', include('okadmin.urls', namespace='okadmin')),
    url('^liitteet/laheta/(?P<upload_group_id>[a-f0-9]{32})'
        '(?P<upload_token>[a-f0-9]{32})/$',
        combo(check_perm(IsAuthenticated), legacy_json_plaintext)(
            UploadAttachmentView.as_view()
        ),
        name='attachtor_file_upload'),
    url('^liitteet/sallitut-paatteet/$', AllowedFileUploadExtensions.as_view(),
        name='allowed_file_upload_extensions'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^', include('survey.urls', namespace='survey')),
    url(r'keskustelut/', include('conversation.urls', namespace='conversation')),
    url(r'^suosikit/', include('favorite.urls', namespace='favorite')),
    url(r'^organisaatiot/', include('organization.urls', namespace='organization')),
    url(r'^palaute/$', FeedbackView.as_view(), name='feedback'),
    url(r'', include('okmoderation.urls', namespace='okmoderation')),
    url(r'^widget/', include('okwidget.urls', namespace='widget')),
    url(r'^tietoa-palvelusta/', include('help.urls', namespace='help')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.STATIC_URL.startswith('http'):
    urlpatterns += staticfiles_urlpatterns('/static/')

handler404 = error_page_not_found

content/templates/scheme/scheme_confirm_delete.html
{% extends "otakantaa/base.html" %}
{% load i18n %}

{% block content %}
<article id="scheme-delete-confirmation" class="well">
    <h1>{% trans "Hankkeen poisto" %}</h1>
    <form method="post">
        {% csrf_token %}
        <p>{% blocktrans with url=object.get_absolute_url %}Poistetaanko hanke <a href="{{ url }}">{{ object }}</a> varmasti?{% endblocktrans %}</p>
        <input type="submit" class="btn btn-default" value="{% trans "Poista" %}" />
        <a class="btn btn-default" href="{% url 'content:scheme_detail' object.pk %}">{% trans "Peruuta" %}</a>
    </form>
</article>
{% endblock content %}

content/templates/scheme/scheme_export_form.html
{% extends "otakantaa/base.html" %}

{% load i18n bootstrap3 %}

{% block title %}{% trans "Hankkeen lataaminen" %}- {{ block.super }}{% endblock title %}

{% block content %}
    {% block content_header %}
        <h1>{{ scheme.title }}</h1>
        <h2>{% blocktrans %}Hankkeen lataaminen {{ format }}-muodossa{% endblocktrans %}</h2>
    {% endblock content_header %}

    {% block content_form %}
        <form class="export-form">
            {% bootstrap_form form %}
            <input type="submit" name="submit" class="btn btn-primary" value="{% blocktrans %}Lataa/Lähetä {{ format }}-tiedosto{% endblocktrans %}">
            <a href="{% url 'content:scheme_detail' scheme_id=scheme.pk %}" class="btn btn-default">{% trans "Takaisin hankkeeseen" %}</a>
        </form>
    {% endblock content_form %}
{% endblock content %}

content/templates/scheme/scheme_interaction_items.html
{% load i18n fontawesome %}

{% for val, text in object.INTERACTION_CHOICES %}
    <li>
        <a href="{% url 'content:scheme_set_interaction' scheme_id=object.pk interaction=val %}" class="ajaxy-link" data-ajaxy-method="post">
            {% if object.interaction == val %}
                {% fa_icon "check" "fw" %}
            {% else %}
                {% fa_icon "fw" %}
            {% endif %} {{ text }}
        </a>
    </li>
{% endfor %}

content/templates/scheme/scheme_list.html
{% load i18n scheme_tags %}

<div class="ajaxy-wrap">
    <div class="container">
        <div class="scheme-list">
            {% for object in object_list %}
                <div class="row display-table">
                    <div class="col-sm-6 display-cell">
                        <h3><a href="{% url 'content:scheme_detail' scheme_id=object.pk %}">{{ object.title }}</a></h3>
                        {% if show_tags %}
                            {{ object.tags.all|join:", " }}
                        {% endif %}
                    </div>
                    <div class="col-sm-3 display-cell participation-stats">
                        {% include 'content/participations_count_container.html' with object=object %}
                    </div>
                    <div class="col-sm-3 display-cell">
                        <div class="owner-list">{% include "scheme/scheme_owners.html" %}</div>
                        <div class="target-municipalities">
                            {{ object.target_municipalities.all|join:", " }}
                        </div>
                        <div class="released-date">{{ object.status_complete }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% if page_obj.has_next %}
        <div class="text-center margin-top-3">
            <a href="{% load_schemes_url page_obj %}" class="btn btn-default load-schemes-btn ajaxy-link" data-ajaxy-target-method="replaceWith">
                {% trans "Näytä lisää" %}
            </a>
        </div>
    {% endif %}
</div>

content/templates/scheme/scheme_main_picture.html
<img src="{{ object.picture_main.url }}" class="img-responsive" alt="{{ object.picture_alt_text }}" title="{{ object.picture_alt_text }}">

content/templates/scheme/scheme_pdf_comment.html
{% load i18n comments %}

{% if comment.is_removed %}
    {% include 'comments/comment_item_removed.html' %}
{% else %}
    {% if comment.title %}
        <div class="comment-title">{{ comment.title }}</div>
    {% endif %}

    <div class="comment-details">
        {% if comment.user %}
            {{ comment.user }}
        {% else %}
            {% trans "Anonyymi kommentoija" %}
        {% endif %}

        {{ comment.created }}

        {% with vote_balance=comment|vote_balance %}
            <span class="thumbs-counter{% if vote_balance < 0 %} negative{% endif %}">{{ vote_balance }}</span>
        {% endwith %}
    </div>

    <p>{{ comment.comment }}</p>
{% endif %}

content/templates/scheme/scheme_publish_preview.html
{% extends 'otakantaa/base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Julkaiseminen" %}</h1>

    <p>{% trans "Julkaise hanke ja siihen liittyvät keskustelut ja kyselyt." %}</p>

    <p><strong>{% trans "Julkaistava hanke" %}:</strong> <a href="{{ object.get_absolute_url }}">{{ object }}</a></p>

    {% if object.participations.surveys.ready_to_publish %}
        <strong>{% trans "Julkaistavat kyselyt" %}</strong>
        <ul>
            {% for s in object.participations.surveys.ready_to_publish %}
                <li><a href="{{ s.get_absolute_url }}">{{ s }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if object.participations.conversations.ready_to_publish %}
        <strong>{% trans "Julkaistavat keskustelut" %}</strong>
        <ul>
            {% for c in object.participations.conversations.ready_to_publish %}
                <li><a href="{{ c.get_absolute_url }}">{{ c }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post" action="{% url 'content:publish_scheme' object.pk %}" class="display-inline">
        {% csrf_token %}
        <button class="btn btn-primary">{% trans "Julkaise" %}</button>
    </form>

    <a href="{% url 'content:scheme_detail' object.pk %}" class="btn btn-default">{% trans "Peruuta" %}</a>
{% endblock content %}

content/templates/scheme/schemes.html
{% extends 'otakantaa/base.html' %}

{% load i18n staticfiles bootstrap3 otakantaa_tags widget_tags %}

{% block precontent %}
    {% include 'otakantaa/temp/kommentointi_painike.html' with toiminto='etusivu' %}

    <a name="search"></a>
    <form id="scheme-search-form" class="form" data-extended-search="{{ extended_search|default:0 }}">
        <div class="container-fluid otakantaa-main-jumbotron">
            <header class="main-header text-center">
                <h1>{% trans "Osallistu keskusteluun. Vaikuta valmisteluun." %}</h1>
                <h2 class="h3">{% trans "Otakantaa.fi-palvelusta löydät ajankohtaiset hankkeet, joihin kaivataan mielipidettäsi." %}</h2>
            </header>

            <div class="container form-components">
                <div class="row scheme-search-text">
                    <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 compact-search-component">
                        {% render_template_to_variable scheme_search_button="scheme/scheme_search_button.html" %}
                        <span class="sr-only">{% trans "Hae hankkeita" %}</span>
                        {% bootstrap_field form.text_with_button button_addon_after=scheme_search_button size="large" bound_css_class="''" %}
                    </div>
                    <div class="col-md-offset-3 col-md-6 extended-search-component">
                        <span class="sr-only">{% trans "Hae hankkeita" %}</span>
                        {% bootstrap_field form.text size="large" bound_css_class="''" %}
                    </div>
                </div>

                <!-- Extended search options -->
                <div class="extended-search-components">
                    <div class="row">
                        <div class="col-md-4">
                            {% bootstrap_field form.municipality bound_css_class="''" %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_field form.tags bound_css_class="''" %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_field form.organization bound_css_class="''" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-6">
                            {% bootstrap_field form.status %}
                        </div>
                        <div class="col-md-4 col-sm-6">
                            {% bootstrap_field form.participations %}
                        </div>
                        <div class="col-md-4 col-sm-6">
                            {% bootstrap_field form.owner_type %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-4 col-md-4 text-center">
                            <button type="submit" class="btn btn-primary btn-lg scheme-search-btn">
                                <span class="glyphicon glyphicon-search"></span> {% trans "Hae" %}
                            </button>
                        </div>
                    </div>
                </div>

                <div class="row extended-search-component">
                    <div class="col-md-4 col-md-offset-4">
                        <p class="text-center hide-extended-form-wrap">
                            <a id="hide-extended-search-form" href="#">{% trans "Piilota lisähakuehdot" %}</a>
                        </p>
                    </div>
                    <div class="col-md-4 text-right">
                        <a target="_blank" href="{{ rss_url|add:"?"|add:request.GET.urlencode }}" class="btn btn-default">RSS</a>
                        <a href="{% url 'widget:scheme_list_modal' %}?{{request.GET.urlencode}}" class="btn btn-default ajaxy-link" data-toggle="ajaxy-modal">
                            <span class="glyphicon glyphicon-cog"></span> {% trans "Widget" %}
                        </a>
                    </div>
                </div>

                <p class="text-center compact-search-component">
                    <a id="show-extended-search-form" href="#">{% trans "Näytä lisähakuehdot" %}</a>
                </p>

                <div class="hidden">
                    {% bootstrap_field form.extended_search %}
                </div>
            </div>
        </div>

        <div class="scheme-result-count">{% blocktrans with results=object_list|length %}Hakuehdoilla löytyi {{ results }} hanketta.{% endblocktrans %}</div>

        <div class="scheme-listing-buttons container form-inline">
            {% bootstrap_field form.sorting %}
            <div class="margin-left-2 display-inline">
                {% bootstrap_field form.display_type %}
            </div>
        </div>
    </form>
{% endblock precontent %}

{% block content %}
    {% include schemes_display_template|default:"scheme/scheme_boxes.html" %}

    <script type="text/javascript" src="{% static 'scheme/js/schemes.js' %}"></script>
{% endblock content %}