account/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView

from libs.djcontrib.conf.urls import decorated_patterns
from libs.djcontrib.utils.decorators import combo
from libs.djcontrib.views.generic import FlashRedirectView
from libs.permitter.decorators import check_perm
from libs.djcontrib.utils.decorators import obj_by_pk

from otakantaa.decorators import legacy_json_plaintext

from . import views
from .models import User
from .perms import CanEditUser, CanViewUserProfile


urlpatterns = [
    url(r'^rekisteroidy/$', views.SignupView.as_view(), name='signup'),
    url(r'^valitse-rekisteroitymistapa/$', views.SignupChoicesView.as_view(),
        name='signup_choices'),
    url(r'^rekisteroidy/facebook/$', views.SignupView.as_view(facebook=True),
        name='signup_facebook'),
    url(r'^kirjaudu-sisaan/$', views.LoginView.as_view(), name='login'),
    url(r'^kirjaudu-ulos/$', views.LogoutView.as_view(), name='logout'),
    url(r'^aktivoi/$', TemplateView.as_view(
        template_name="account/authentication/signup_activation.html"
    ), name='activate'),
    url(r'^vahvista-sahkoposti/(?P<token>\w{26,50})/$',
        views.EmailConfirmationView.as_view(), name='confirm_email'),
    url(r'^(?P<user_id>\d+)/$',
        obj_by_pk(User, 'user_id')(check_perm(CanViewUserProfile)(
            views.UserProfileView.as_view())), name='profile'),
    url(r'(?P<user_id>\d+)/lista/$', views.UserProfileSchemeListView.as_view(),
        name='scheme_list'),
    url(r'^nollaa-salasana/$', auth.password_reset, name='reset_password',
        kwargs={
            'template_name': 'account/authentication/user_reset_password.html',
            'email_template_name': 'account/email/password_reset.txt',
            'subject_template_name': 'account/email/password_reset_title.txt',
            'post_reset_redirect': 'account:password_reset_done',
        }),
    url(r'^nollaa-salasana/linkki-lahetetty/$', auth.password_reset_done,
        name='password_reset_done',
        kwargs={'template_name':
                'account/authentication/user_reset_password_link_sent.html'}),
    url(r'^nollaa-salasana/vahvista/(?P<uidb64>[0-9A-Za-z_\-]+)'
        '/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth.password_reset_confirm,
        name='password_reset_confirm',
        kwargs={
            'template_name': 'account/authentication/user_reset_password_confirm.html',
            'post_reset_redirect': 'account:password_reset_ready'
        }),
    url(r'^nollaa-salasana/valmis/$',
        FlashRedirectView.as_view(
            message=_("Salasanasi on vaihdettu. Voit nyt kirjautua sisään "
                      "käyttäen uutta salasanaasi."),
            pattern_name='account:login',
            permanent=True
        ), name='password_reset_ready')
]

urlpatterns += decorated_patterns(
    '',
    combo(obj_by_pk(User, 'user_id'), check_perm(CanEditUser)),
    url(r'(?P<user_id>\d+)/asetukset/$', views.UserSettingsView.as_view(),
        name='settings'),
    url(r'(?P<user_id>\d+)/nayta-asetukset/',
        views.UserSettingsDetailView.as_view(),
        name='settings_detail'),
    url(r'(?P<user_id>\d+)/muokkaa-asetukset/',
        views.UserSettingsEditView.as_view(),
        name='settings_edit'),
    url(r'(?P<user_id>\d+)/asetukset/kuva/$', views.ProfilePictureView.as_view(),
        name='profile_picture'),
    url(r'(?P<user_id>\d+)/asetukset/kuva/muokkaa/$',
        legacy_json_plaintext(views.EditProfilePictureView.as_view()),
        name='edit_profile_picture'),
    url(r'(?P<user_id>\d+)/asetukset/kuva/poista/$',
        views.DeleteProfilePictureView.as_view(),
        name='delete_profile_picture'),
    url(r'(?P<user_id>\d+)/sulje/$',
        views.CloseAccountView.as_view(logout=True),
        name='close'),
    url(r'^(?P<user_id>\d+)/salasanan-vaihto/$', views.UserChangePasswordView.as_view(),
        name='password'),
    url(r'^(?P<user_id>\d+)/viestit/$',
        views.MessagesListView.as_view(),
        name="messages"),
    url(r'^(?P<user_id>\d+)/viestit/(?P<message_id>\d+)/$',
        views.MessageDetailView.as_view(),
        name="show_message"),
    url(r'^(?P<user_id>\d+)/viestit/(?P<message_id>\d+)/#(?P<anchor>[-_\w]+)$',
        views.MessageDetailView.as_view(),
        name="show_message"),
    url(r'^(?P<user_id>\d+)/viestit/(?P<message_id>\d+)/vastaa/$',
        views.CreateMessageView.as_view(),
        name="respond_message"),
    url(r'^(?P<user_id>\d+)/viestit/uusi/$',
        views.CreateMessageView.as_view(),
        name="create_message"),
    url(r'^(?P<user_id>\d+)/viestit/uusi/(?P<scheme_id>\d+)/$',
        views.CreateMessageView.as_view(),
        name="create_message"),
    url(r'^(?P<user_id>\d+)/viestit/taulu/$',
        views.MessagesListView.as_view(template_name="account/messages/list_table.html"),
        name="messages_table"),
    url(r'^(?P<user_id>\d+)/viestit/(?P<message_id>\d+)/poista/$',
        views.DeleteMessageView.as_view(),
        name="delete_message"),
    url(r'(?P<user_id>\d+)/muokkaa-ilmoitukset/$',
        views.NotificationOptionsEditView.as_view(),
        name='notification_options_edit'),
    url(r'(?P<user_id>\d+)/nayta-ilmoitukset/$',
        views.NotificationOptionsDetailView.as_view(),
        name='notification_options_detail'),
)

content/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import url, include

from libs.djcontrib.conf.urls import decorated_patterns
from libs.djcontrib.utils.decorators import obj_by_pk, combo
from libs.permitter.decorators import check_perm

from otakantaa.decorators import legacy_json_plaintext
from otakantaa.perms import IsAuthenticated

from . import views, forms
from .perms import CanPublishScheme, CanRevertSchemeToDraft, CanAcceptInvitation, \
    CanCloseScheme, CanReopenScheme, CanDeleteScheme, CanViewScheme, CanEditScheme, \
    CanExportSchemePdf, CanExportSchemeExcel, CanExportSchemeWord
from .models import Scheme

scheme_as_obj = obj_by_pk(Scheme, 'scheme_id')
interaction_choices = [str(k) for k, v in Scheme.INTERACTION_CHOICES]

SCHEME_FRAGMENT_URLS = (
    # (url part, template name/url name part, form_class, view_class)
    (r'kuva',           'picture',          forms.EditSchemePictureForm),
    (r'otsikko',        'title',            forms.EditSchemeTitleForm),
    (r'kuvaus',         'description',      forms.EditSchemeDescriptionForm),
    (r'ingressi',       'lead_text',        forms.EditSchemeLeadTextForm),
    (r'yhteenveto',     'summary',          forms.EditSchemeSummaryForm),
    (r'omistajat',      'owners',           None, views.SchemeOwnersEditView),
    (r'aiheet',         'tags',             forms.EditSchemeTagsForm),
    (r'kunnat',         'municipalities',   forms.EditSchemeMunicipalitiesForm),
)

partial_detail_urls = [
    url(r'hankkeet/(?P<scheme_id>\d+)/nayta/%s/$' % u[0],
        views.ContentPartialDetailView.as_view(),
        name='scheme_detail_%s' % u[1],
        kwargs={'template_name': 'content/parts/scheme_detail_%s.html' % u[1]})
    for u in SCHEME_FRAGMENT_URLS
]

partial_edit_patterns = [
    url(r'hankkeet/(?P<scheme_id>\d+)/muokkaa/%s/$' % u[0],
        legacy_json_plaintext((u[3] if len(u) > 3 else
        views.SchemePartialEditView).as_view()), name='edit_scheme_%s' % u[1],
        kwargs={'template_name': 'content/parts/scheme_edit_%s_form.html' % u[1],
                'form_class': u[2], 'fragment': u[1]})
    for u in SCHEME_FRAGMENT_URLS
]

urlpatterns = [
    url(r'hankkeet/uusi/$', check_perm(IsAuthenticated)(views.CreateSchemeView.as_view()),
        name='create_scheme'),
    url(r'hankkeet/(?P<scheme_id>\d+)/julkaise/$',
        scheme_as_obj(check_perm(CanPublishScheme)(views.PublishSchemeView.as_view())),
        name='publish_scheme'),
    url(r'hankkeet/(?P<scheme_id>\d+)/poista/$',
        scheme_as_obj(check_perm(CanDeleteScheme)(views.DeleteSchemeView.as_view())),
        name='delete_scheme'),
    url(r'hankkeet/(?P<scheme_id>\d+)/julkaiseminen/$',
        scheme_as_obj(check_perm(CanPublishScheme)(
            views.TryPublishSchemeView.as_view())), name='try_publish'),
    url(r'hankkeet/(?P<scheme_id>\d+)/paattaminen/$',
        scheme_as_obj(check_perm(CanCloseScheme)(
            views.TryCloseSchemeView.as_view())), name='try_close'),
    url(r'hankkeet/(?P<scheme_id>\d+)/avaa/$',
        scheme_as_obj(check_perm(CanReopenScheme)(views.ReOpenSchemeView.as_view())),
        name='reopen_scheme'),
    url(r'hankkeet/(?P<scheme_id>\d+)/muuta-luonnokseksi/$',
        scheme_as_obj(check_perm(CanRevertSchemeToDraft)(
            views.RevertSchemeToDraftView.as_view())), name='revert_scheme_to_draft'),
    url(r'hankkeet/(?P<scheme_id>\d+)/vahvista-kutsu/(?P<scheme_owner_id>\d+)/',
        scheme_as_obj(check_perm(CanAcceptInvitation)(
            views.SchemeOwnerInvitationView.as_view())), name="owner_invitation"),
    url(r'hankkeet/(?P<scheme_id>\d+)/aseta-osallistujat/(?P<interaction>[' +
        ",".join(interaction_choices) + '])/$',
        scheme_as_obj(check_perm(CanEditScheme)(views.SetInteractionView.as_view())),
        name='scheme_set_interaction'),
    url(r'^rss/$', views.SchemeFeed(), name='rss'),
    url(r'^hankkeet/lataa-lisaa/$', views.LoadSchemesView.as_view(),
        name='load_schemes'),

    # Export.
    url(r'hankkeet/(?P<scheme_id>\d+)/pdf/',
        scheme_as_obj(check_perm(CanExportSchemePdf)(
            views.SchemePdfExportView.as_view()
        )), name="scheme_pdf_export"),
    url(r'hankkeet/(?P<scheme_id>\d+)/excel/',
        scheme_as_obj(check_perm(CanExportSchemeExcel)(
            views.ParticipationExcelExportView.as_view()
        )), name="participation_excel_export"),
    url(r'hankkeet/(?P<scheme_id>\d+)/word/',
        scheme_as_obj(check_perm(CanExportSchemeWord)(
            views.SchemeWordExportView.as_view()
        )), name="participation_word_export"),
]

urlpatterns += decorated_patterns('', scheme_as_obj,
    url(r'hankkeet/(?P<scheme_id>\d+)/osallistuminen/',
        include('content.urls_participation', namespace='participation')),
)

urlpatterns += decorated_patterns('', combo(scheme_as_obj, check_perm(CanViewScheme)),
    url(r'^hankkeet/(?P<scheme_id>\d+)/$', views.SchemeDetailView.as_view(),
        name='scheme_detail'),
    url(r'hankkeet/(?P<scheme_id>\d+)/liitteet/nayta/$', views.AttachmentsDetailView.
        as_view(), name='attachment_list'),
    *partial_detail_urls
)

urlpatterns += decorated_patterns('', combo(scheme_as_obj, check_perm(CanEditScheme)),
    url(r'hankkeet/(?P<scheme_id>\d+)/poista/kuva/$',
        views.DeleteSchemePictureView.as_view(), name='delete_scheme_picture'),
    url(r'hankkeet/(?P<scheme_id>\d+)/liitteet/muokkaa/$',
        views.UploadMultipleAttachmentsSchemeView.as_view(), name='add_attachments'),
    url(r'hankkeet/(?P<scheme_id>\d+)/liitteet/(?P<upload_id>\d+)/poista/$',
        views.DeleteAttachmentView.as_view(), name='delete_attachment'),
    url(r'hankkeet/(?P<scheme_id>\d+)/esimoderointi/(?P<premoderation_state>(0|1))/$',
        views.PremoderationToggleView.as_view(), name='toggle_premoderation'),
    url(r'^hankkeet/(?P<scheme_id>\d+)/twitter-hakusana/$',
        views.SchemeTwitterSearchFormView.as_view(), name="twitter_search"),
    *partial_edit_patterns
)

help/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views
from .models import Instruction

link_slug_pattern = '{0}|{1}'.format(Instruction.TYPE_PRIVACY_POLICY,
                                     Instruction.TYPE_CONTACT_DETAILS)

urlpatterns = [
    url(r'^$', views.InstructionDetailFirst.as_view(permanent=True), name='instruction_list'),
    url(r'(?P<pk>\d+)/$', views.InstructionDetail.as_view(), name='instruction_detail'),
    url(r'^linkki/(?P<slug>%s)/$' % link_slug_pattern,
        views.LinkedInstructionRedirectView.as_view(permanent=True),
        name='linked_instruction_redirect'),
]

libs/attachtor/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url('^(?P<upload_group_id>[a-f0-9]{32})(?P<upload_token>[a-f0-9]{32})/$',
        views.UploadAttachmentView.as_view(),
        name='attachtor_file_upload')
)

okwidget/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^hankkeet/$', views.SchemeListWidgetView.as_view(),
        name="scheme_list"),
    url(r'^hankkeet/modal/$', views.SchemeListWidgetModalView.as_view(),
        name="scheme_list_modal"),
    url(r'^hankkeet/(?P<scheme_id>\d+)/$',
        views.SchemeWidgetView.as_view(), name="scheme"),
    url(r'^hankkeet/(?P<scheme_id>\d+)/modal/$',
        views.SchemeWidgetModalView.as_view(), name="scheme_modal"),
]

otakantaa/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic.base import RedirectView

from content.views import UploadAttachmentView, SchemesView

from libs.djcontrib.utils.decorators import combo
from libs.permitter.decorators import check_perm
from libs.moderation.helpers import auto_discover

from okmessages.views import FeedbackView

from .views import AllowedFileUploadExtensions, error_page_not_found
from .decorators import legacy_json_plaintext
from .perms import IsAuthenticated


auto_discover()

urlpatterns = [
    url('^api/$', RedirectView.as_view(url='/api/open/0.1/', permanent=False)),  # HACK
    url(r'^api/open/', include('openapi.urls', namespace='openapi')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', SchemesView.as_view(), name='schemes'),
    url(r'^kayttaja/', include('account.urls', namespace='account')),
    url(r'^', include('content.urls', namespace='content')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^hallinta/', include('okadmin.urls', namespace='okadmin')),
    url('^liitteet/laheta/(?P<upload_group_id>[a-f0-9]{32})'
        '(?P<upload_token>[a-f0-9]{32})/$',
        combo(check_perm(IsAuthenticated), legacy_json_plaintext)(
            UploadAttachmentView.as_view()
        ),
        name='attachtor_file_upload'),
    url('^liitteet/sallitut-paatteet/$', AllowedFileUploadExtensions.as_view(),
        name='allowed_file_upload_extensions'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^', include('survey.urls', namespace='survey')),
    url(r'keskustelut/', include('conversation.urls', namespace='conversation')),
    url(r'^suosikit/', include('favorite.urls', namespace='favorite')),
    url(r'^organisaatiot/', include('organization.urls', namespace='organization')),
    url(r'^palaute/$', FeedbackView.as_view(), name='feedback'),
    url(r'', include('okmoderation.urls', namespace='okmoderation')),
    url(r'^widget/', include('okwidget.urls', namespace='widget')),
    url(r'^tietoa-palvelusta/', include('help.urls', namespace='help')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.STATIC_URL.startswith('http'):
    urlpatterns += staticfiles_urlpatterns('/static/')

handler404 = error_page_not_found

libs/attachtor/forms/widgets.py
# coding=utf-8

from __future__ import unicode_literals

import json

from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.translation import get_language

from redactor.widgets import RedactorEditor

from ..utils import get_upload_token


class RedactorAttachtorWidget(RedactorEditor):
    init_js = '''<script type="text/javascript">
                    jQuery(document).ready(function(){
                        var $field = jQuery("#%s");
                        options = %s;
                        options.imageUploadErrorCallback =
                        options.fileUploadErrorCallback = function(json){
                            alert(json.error);
                        };
                        $field.redactor(options);
                    });
                 </script>
              '''

    def __init__(self, *args, **kwargs):
        super(RedactorAttachtorWidget, self).__init__(*args, **kwargs)
        self.upload_group_id = kwargs.pop('upload_group_id', None)

    def _get_upload_group_id(self):
        return self._upload_group_id

    def _set_upload_group_id(self, val):
        self._upload_group_id = val

    upload_group_id = property(_get_upload_group_id, _set_upload_group_id)

    def get_options(self):
        options = getattr(settings, 'REDACTOR', {}).copy()
        options.update(self.custom_options)
        upload_url = reverse('attachtor_file_upload', kwargs={
            'upload_group_id': self.upload_group_id,
            'upload_token': get_upload_token(self.upload_group_id)
        })
        if self.allow_file_upload:
            options.setdefault('fileUpload', upload_url)
        if self.allow_image_upload:
            options.setdefault('imageUpload', upload_url)
        options['lang'] = get_language()
        return json.dumps(options)

okwidget/templates/widget/scheme_list_widget_content.html
{% extends "widget/widget_content_base.html" %}

{% load i18n %}

{% block widget_results %}
    {% for scheme in object_list %}
        <div class="widget-item">
            <div class="widget-item-title">
                <a href="{% url 'content:scheme_detail' scheme.pk %}" target="_blank">
                    {{ scheme.title }}
                </a>
            </div>
            <div class="info-text">
                {% include "widget/widget_scheme_owners.html" %} |
                {{ scheme.published|date:"d.m.Y" }}
            </div>
        </div>
    {% endfor %}
{% endblock widget_results %}

{% block widget_no_results %}{% trans "Hankkeita ei löytynyt." %}{% endblock widget_no_results %}

okwidget/templates/widget/scheme_list_widget_modal.html
{% extends "widget/widget_modal.html" %}

{% load bootstrap3 %}

{% block widget_fields %}
    {{ block.super }}
    {% bootstrap_field form.language bound_css_class=" " error_css_class=" " %}
{% endblock widget_fields %}

okwidget/templates/widget/scheme_widget_content.html
{% extends "widget/widget_content_base.html" %}

{% load i18n fontawesome %}

{% block widget_results %}
    <ul class="scheme-content-list scheme-content-list-conversation">
        {% for comment in object_list %}
            <div class="widget-item">
                {% include "scheme/scheme_conversation_list_item.html" %}
            </div>
        {% endfor %}
    </ul>
{% endblock widget_results %}

{% block widget_no_results %}{% trans "Kommentteja ei löytynyt." %}{% endblock widget_no_results %}

{% block widget_footer %}
{% endblock widget_footer %}

okwidget/templates/widget/widget.html
<!DOCTYPE html>
<html lang="en">
    {% load i18n compress staticfiles %}
    <head>
        <meta charset="utf-8">
        <title>Otakantaa.fi-widget</title>

        <link href='https://fonts.googleapis.com/css?family=PT+Sans:400,700|PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>

        {% block css %}
            {% compress css %}
                <link rel="stylesheet" href="{% static "otakantaa/scss/otakantaa.scss" %}" type="text/x-scss">
            {% endcompress %}
        {% endblock css %}
    </head>
    <body style="background-color: white;">
        {% include content_template_name %}
    </body>
</html>

okwidget/templates/widget/widget_content_base.html
{% load i18n staticfiles bootstrap3 %}

<main class="widget">
    <header class="widget-header">
        <a href="{% url 'schemes' %}">
            <img src="{% static 'otakantaa/img/logo_s_'|add:request.LANGUAGE_CODE|add:'.png' %}" alt="{% trans "Otakantaa.fi" %}-{% trans "logo" %}">
        </a>
    </header>

    {% for field, errors in form.errors.iteritems %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                {{ field }}
            </div>
            <ul class="list-group">
                {% for error in errors %}
                    <li class="list-group-item">{{ error }}</li>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    {% block widget_results %}
    {% endblock widget_results %}

    {% if not object_list %}
        <div class="widget-no-results">
            <i>{% block widget_no_results %}{% trans "Ei tuloksia." %}{% endblock widget_no_results %}</i>
        </div>
    {% endif %}

    {% block widget_footer %}
        <footer>
            <a href="{% url 'schemes' %}?{{request.GET.urlencode}}" class="btn btn-default btn-green" target="_blank">
                {% trans "Näytä kaikki" %}
            </a>
        </footer>
    {% endblock widget_footer %}
</main>

okwidget/templates/widget/widget_modal.html
{% load i18n bootstrap3 staticfiles widget_tags %}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">{% trans "Widget" %}</h4>
</div>
<div class="modal-body">
    {% if widget_help_text %}
        <p>{{ widget_help_text }}</p>
    {% endif %}
    <p>{% trans "Alareunasta löydät iframe-koodin, jonka voit upottaa verkkosivuillesi." %}</p>

    <div class="widget-modal-refreshers">
        {% block widget_fields %}
            {% bootstrap_field form.limit bound_css_class=" " error_css_class=" " %}
        {% endblock widget_fields %}
    </div>

    <label class="control-label">{% trans "Esikatselu" %}</label>
    <div class="widget-modal-preview" data-widget-url="{{ widget_url }}" data-base-url="{{ request.get_host }}">
        {% include content_template_name %}
    </div>

    <label class="control-label">{% trans "Koodi" %}</label>
    <textarea class="widget-modal-code form-control"><iframe src="{{ request.get_host }}{{ widget_url }}"></iframe></textarea>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Sulje" %}</button>
</div>

<script type="text/javascript" src="{% static 'widget/js/widget_modal.js' %}"></script>

okwidget/templates/widget/widget_scheme_owners.html
{% load scheme_tags %}

{% scheme_owner_organization scheme as organization %}

{% if scheme.written_as_organization %}
    {% for organization in scheme.owners.unique_organizations.all %}
        <a href="{{ organization.get_absolute_url }}">{{ organization }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
{% else %}
    {% for owner in scheme.owners.all %}
        <a href="{% url 'account:profile' owner.pk %}" target="_blank">{{ owner }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
{% endif %}