help/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views
from .models import Instruction

link_slug_pattern = '{0}|{1}'.format(Instruction.TYPE_PRIVACY_POLICY,
                                     Instruction.TYPE_CONTACT_DETAILS)

urlpatterns = [
    url(r'^$', views.InstructionDetailFirst.as_view(permanent=True), name='instruction_list'),
    url(r'(?P<pk>\d+)/$', views.InstructionDetail.as_view(), name='instruction_detail'),
    url(r'^linkki/(?P<slug>%s)/$' % link_slug_pattern,
        views.LinkedInstructionRedirectView.as_view(permanent=True),
        name='linked_instruction_redirect'),
]

libs/attachtor/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url('^(?P<upload_group_id>[a-f0-9]{32})(?P<upload_token>[a-f0-9]{32})/$',
        views.UploadAttachmentView.as_view(),
        name='attachtor_file_upload')
)

otakantaa/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic.base import RedirectView

from content.views import UploadAttachmentView, SchemesView

from libs.djcontrib.utils.decorators import combo
from libs.permitter.decorators import check_perm
from libs.moderation.helpers import auto_discover

from okmessages.views import FeedbackView

from .views import AllowedFileUploadExtensions, error_page_not_found
from .decorators import legacy_json_plaintext
from .perms import IsAuthenticated


auto_discover()

urlpatterns = [
    url('^api/$', RedirectView.as_view(url='/api/open/0.1/', permanent=False)),  # HACK
    url(r'^api/open/', include('openapi.urls', namespace='openapi')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', SchemesView.as_view(), name='schemes'),
    url(r'^kayttaja/', include('account.urls', namespace='account')),
    url(r'^', include('content.urls', namespace='content')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^hallinta/', include('okadmin.urls', namespace='okadmin')),
    url('^liitteet/laheta/(?P<upload_group_id>[a-f0-9]{32})'
        '(?P<upload_token>[a-f0-9]{32})/$',
        combo(check_perm(IsAuthenticated), legacy_json_plaintext)(
            UploadAttachmentView.as_view()
        ),
        name='attachtor_file_upload'),
    url('^liitteet/sallitut-paatteet/$', AllowedFileUploadExtensions.as_view(),
        name='allowed_file_upload_extensions'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^', include('survey.urls', namespace='survey')),
    url(r'keskustelut/', include('conversation.urls', namespace='conversation')),
    url(r'^suosikit/', include('favorite.urls', namespace='favorite')),
    url(r'^organisaatiot/', include('organization.urls', namespace='organization')),
    url(r'^palaute/$', FeedbackView.as_view(), name='feedback'),
    url(r'', include('okmoderation.urls', namespace='okmoderation')),
    url(r'^widget/', include('okwidget.urls', namespace='widget')),
    url(r'^tietoa-palvelusta/', include('help.urls', namespace='help')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.STATIC_URL.startswith('http'):
    urlpatterns += staticfiles_urlpatterns('/static/')

handler404 = error_page_not_found

survey/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url, include

from libs.djcontrib.conf.urls import decorated_patterns
from libs.djcontrib.utils.decorators import combo, obj_by_pk
from libs.permitter.decorators import check_perm

from . import views
from .models import Survey, SurveyQuestion
from .perms import CanEditSurvey, CanAnswerSurvey, ShowSurveyResults


survey_as_obj = obj_by_pk(Survey, "survey_id")
question_as_obj = obj_by_pk(SurveyQuestion, "question_id")

urlpatterns = decorated_patterns(
    "",
    combo(survey_as_obj, check_perm(CanEditSurvey)),

    url(r"^kysely/(?P<survey_id>\d+)/", include(patterns(
        "",
        url(r"^elementti/(?P<element_id>\d+)/", include(patterns(
            "",
            url(r"^nosta/$",
                views.SurveyElementMoveView.as_view(direction="up"), name="move_up"),
            url(r"^laske/$",
                views.SurveyElementMoveView.as_view(direction="down"), name="move_down"),
            url(r"^poista/$", views.SurveyElementDeleteView.as_view(), name="delete"),
        ), namespace="element")),

        url(r"^sivu/uusi/$", views.SurveyPageCreateView.as_view(), name="create_page"),

        url(r"^valiotsikko/", include(patterns(
            "",
            url(r"^uusi/$",
                views.SurveySubtitleFormView.as_view(), name="create_subtitle"),
            url(r"^(?P<subtitle_id>\d+)/muokkaa/$",
                views.SurveySubtitleFormView.as_view(), name="update_subtitle"),
            url(r"^(?P<subtitle_id>\d+)/$",
                views.SurveySubtitleAnswerView.as_view(), name="subtitle"),
        ))),

        url(r"^kysymys/", include(patterns(
            "survey.views",
            url(
                name="question",
                regex="^(?P<question_id>\d+)/$",
                view="question_answer",
            ),
            url(
                name="update_question",
                regex="^(?P<question_id>\d+)/muokkaa/$",
                view="question_form",
            ),
            url(
                name="create_text_question",
                regex=r"^uusi/teksti/$",
                view="question_form_text",
            ),
            url(
                name="create_number_question",
                regex="^uusi/numero/$",
                view="question_form_number",
            ),
            url(
                name="create_radio_question",
                regex="^uusi/yksivalinta/$",
                view="question_form_radio",
            ),
            url(
                name="create_checkbox_question",
                regex="^uusi/monivalinta/$",
                view="question_form_checkbox",
            ),
        ))),
    ))),
)

urlpatterns += [
    url(r"^kysely/(?P<survey_id>\d+)/laheta/$",
        survey_as_obj(check_perm(CanAnswerSurvey)(views.SurveySubmissionView.as_view())),
        name="submit"),
    url(r"^kysely/(?P<survey_id>\d+)/kysymys/(?P<question_id>\d+)/vastaukset/$",
        survey_as_obj(check_perm(ShowSurveyResults)
                      (views.SurveyQuestionAnswerListView.as_view())),
        name="question_answers"),
]

survey/views.py
# coding=utf-8

from __future__ import unicode_literals

from httplib import RESET_CONTENT

from django.core.urlresolvers import reverse
from django.contrib import messages
from django.db.models.aggregates import Max
from django.http.response import HttpResponse
from django.utils.translation import ugettext as _
from django.views.generic.base import View, ContextMixin, TemplateResponseMixin
from django.views.generic.detail import SingleObjectMixin, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from . import models, forms
from .utils import set_submitter_cookie, get_submitter, get_client_identifier


class SurveyElementMoveView(SingleObjectMixin, View):
    model = models.SurveyElement
    queryset = models.SurveyElement.objects.non_polymorphic()
    pk_url_kwarg = "element_id"
    direction = None

    def post(self, request, *args, **kwargs):
        element = self.get_object()

        if self.direction == "up":
            element.up()
        elif self.direction == "down":
            element.down()
        else:
            return HttpResponse("Unkown direction.", status=400)

        return HttpResponse(status=RESET_CONTENT)


class SurveyElementDeleteView(DeleteView):
    model = models.SurveyElement
    queryset = models.SurveyElement.objects.non_polymorphic()
    pk_url_kwarg = "element_id"

    def delete(self, request, *args, **kwargs):
        element = self.get_object()
        element.delete()
        return HttpResponse(status=RESET_CONTENT)


class SurveyPageCreateView(CreateView):
    model = models.SurveyPage
    fields = ["survey"]
    template_name = "survey/answer_mode/page.html"
    context_object_name = "element"
    http_method_names = ["post"]

    def get_context_data(self, **kwargs):
        context = super(SurveyPageCreateView, self).get_context_data(**kwargs)
        context["edit_mode"] = True
        return context

    def get_form_kwargs(self):
        kwargs = super(SurveyPageCreateView, self).get_form_kwargs()
        kwargs["data"] = kwargs["data"].copy()
        kwargs["data"]["survey"] = self.kwargs["survey_id"]
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        return self.render_to_response(self.get_context_data(form=form))


class SurveySubtitleFormView(UpdateView):
    """ Create and update view for survey subtitles. """
    queryset = models.SurveySubtitle.objects.select_related("survey")
    form_class = forms.SurveySubtitleForm
    pk_url_kwarg = "subtitle_id"
    template_name = "survey/edit_mode/subtitle.html"
    context_object_name = "element"

    def get_prefix_id(self):
        given_prefix_id = self.request.GET.get("prefix_id")
        if given_prefix_id is not None:
            return given_prefix_id
        given_prefix_id = self.request.POST.get("prefix_id")
        if given_prefix_id is not None:
            return given_prefix_id

    def get_prefix(self):
        given_prefix_id = self.get_prefix_id()
        if given_prefix_id is not None:
            return "new_subtitle_{}".format(given_prefix_id)
        return "subtitle_{}".format(self.object.pk)

    def get_initial(self):
        initial = super(SurveySubtitleFormView, self).get_initial()
        if self.request.method.lower() == "get" and self.has_url_pk() is False:
            initial["order"] = models.SurveyElement.objects \
                .filter(survey_id=self.kwargs["survey_id"]) \
                .aggregate(Max("order")) \
                .get("order__max")

            if initial['order'] is int:
                initial['order'] += 1

        initial["prefix_id"] = self.get_prefix_id() or self.object.pk
        return initial

    def get_context_data(self, **kwargs):
        context = super(SurveySubtitleFormView, self).get_context_data(**kwargs)
        context["survey_id"] = self.kwargs["survey_id"]
        context["edit_mode"] = True
        context.setdefault("new", True)
        context["prefix_id"] = self.get_prefix_id() or self.object.pk
        return context

    def get_object(self, queryset=None):
        if self.has_url_pk() is False:
            return models.SurveySubtitle(survey_id=self.kwargs["survey_id"])
        return super(SurveySubtitleFormView, self).get_object(queryset)

    def has_url_pk(self):
        return bool(self.kwargs.get(self.pk_url_kwarg, None))

    def form_invalid(self, form):
        context = self.get_context_data(form=form, new=self.has_url_pk())
        return self.render_to_response(context)

    def form_valid(self, form):
        self.object = form.save()
        self.template_name = "survey/answer_mode/subtitle.html"
        context = self.get_context_data(form=form, new=False)
        return self.render_to_response(context)


class SurveySubtitleAnswerView(DetailView):
    model = models.SurveySubtitle
    template_name = "survey/answer_mode/subtitle.html"
    pk_url_kwarg = "subtitle_id"
    context_object_name = "element"

    def get_context_data(self, **kwargs):
        context = super(SurveySubtitleAnswerView, self).get_context_data(**kwargs)
        context["edit_mode"] = True
        return context


class SurveyQuestionFormView(UpdateView):
    """
    Expects type parameter in get or post data, depending on the request method.
    """
    queryset = models.SurveyQuestion.objects.select_related("survey")
    form_class = forms.SurveyQuestionForm
    pk_url_kwarg = "question_id"
    template_name = "survey/edit_mode/question.html"
    context_object_name = "element"
    question_type = None

    def get_prefix_id(self):
        given_prefix_id = self.request.GET.get("prefix_id")
        if given_prefix_id is not None:
            return given_prefix_id
        given_prefix_id = self.request.POST.get("prefix_id")
        if given_prefix_id is not None:
            return given_prefix_id

    def get_prefix(self):
        given_prefix_id = self.get_prefix_id()
        if given_prefix_id is not None:
            return "new_question_{}".format(given_prefix_id)
        return "question_{}".format(self.object.pk)

    def get_initial(self):
        initial = super(SurveyQuestionFormView, self).get_initial()
        initial["type"] = self.get_question_type()
        if self.request.method.lower() == "get" and self.has_url_pk() is False:
            max_order = models.SurveyElement.objects \
                .filter(survey_id=self.kwargs["survey_id"]) \
                .aggregate(Max("order")) \
                .get("order__max")
            initial["order"] = max_order + 1 if max_order is not None else 0
        initial["prefix_id"] = self.get_prefix_id() or self.object.pk
        return initial

    def get_form_kwargs(self):
        kwargs = super(SurveyQuestionFormView, self).get_form_kwargs()
        kwargs["question_type"] = self.get_question_type()
        return kwargs

    def is_option_input(self):
        return self.get_question_type() in [models.SurveyQuestion.TYPE_CHECKBOX,
                                            models.SurveyQuestion.TYPE_RADIO]

    def get_question_type(self):
        if self.question_type:
            return self.question_type
        self.question_type = self.get_object().type
        return self.question_type

    def get_type_display(self):
        if self.question_type:
            return dict(models.SurveyQuestion.TYPE_CHOICES)[self.get_question_type()]
        return self.get_object().get_type_display()

    def get_context_data(self, **kwargs):
        context = super(SurveyQuestionFormView, self).get_context_data(**kwargs)
        context["is_option_input"] = self.is_option_input()
        context["question_type_display"] = self.get_type_display()
        context["survey_id"] = self.kwargs["survey_id"]
        context["edit_mode"] = True
        context.setdefault("new", True)
        context["prefix_id"] = self.get_prefix_id() or self.object.pk
        return context

    def get_object(self, queryset=None):
        if self.has_url_pk() is False:
            return models.SurveyQuestion(survey_id=self.kwargs["survey_id"])
        return super(SurveyQuestionFormView, self).get_object(queryset)

    def has_url_pk(self):
        return bool(self.kwargs.get(self.pk_url_kwarg, None))

    def form_invalid(self, form):
        context = self.get_context_data(form=form, new=not self.has_url_pk())
        return self.render_to_response(context)

    def form_valid(self, form):
        self.object = form.save()
        self.template_name = "survey/answer_mode/question.html"
        answer_form_class = forms.QUESTION_ANSWER_FORMS[self.object.type]
        form = answer_form_class(
            question=self.object,
            prefix="question_{}".format(self.object.pk)
        )
        context = self.get_context_data(form=form, new=False)
        return self.render_to_response(context)

question_form = SurveyQuestionFormView.as_view()
question_form_text = SurveyQuestionFormView.as_view(
    question_type=models.SurveyQuestion.TYPE_TEXT)
question_form_number = SurveyQuestionFormView.as_view(
    question_type=models.SurveyQuestion.TYPE_NUMBER)
question_form_radio = SurveyQuestionFormView.as_view(
    question_type=models.SurveyQuestion.TYPE_RADIO)
question_form_checkbox = SurveyQuestionFormView.as_view(
    question_type=models.SurveyQuestion.TYPE_CHECKBOX)


class SurveyQuestionAnswerView(DetailView):
    model = models.SurveyQuestion
    template_name = "survey/answer_mode/question.html"
    pk_url_kwarg = "question_id"
    context_object_name = "element"

    def get_context_data(self, **kwargs):
        context = super(SurveyQuestionAnswerView, self).get_context_data(**kwargs)
        context["edit_mode"] = True
        form_class = forms.QUESTION_ANSWER_FORMS[self.object.type]
        form = form_class(question=self.object,
                          prefix="question_{}".format(self.object.pk))
        context["form"] = form
        return context

survey/templates/survey/edit_mode/element_buttons.html
{% load i18n %}

<a href="{% url 'survey:element:move_up' survey_id=element.survey.pk element_id=element.pk %}" class="btn btn-default survey-element-up" title="{% trans 'Nosta' %}"><span class="glyphicon glyphicon-arrow-up"></span></a>
<a href="{% url 'survey:element:move_down' survey_id=element.survey.pk element_id=element.pk %}" class="btn btn-default survey-element-down" title="{% trans 'Laske' %}"><span class="glyphicon glyphicon-arrow-down"></span></a>
<a href="{% url 'survey:element:delete' survey_id=element.survey.pk element_id=element.pk %}" class="btn btn-danger survey-element-delete" title="{% trans 'Poista' %}"><span class="glyphicon glyphicon-remove"></span></a>

survey/templates/survey/edit_mode/question.html
{% load i18n bootstrap3 %}

<div class="survey-element survey-element-mode-edit survey-element-question ajaxy-wrap {% if new %}survey-element-new{% endif %}">
    <form action="{{ request.path }}" class="ajaxy-form" method="post" data-ajaxy-target-method="replaceWith" novalidate>
        <div class="survey-question-title">{{ question_type_display }}</div>

        {% csrf_token %}
        {% bootstrap_field form.text %}
        {% bootstrap_field form.instruction_text %}
        {% bootstrap_field form.required %}
        {% bootstrap_field form.type %}

        {% if is_option_input %}
            <div class="survey-question-options">
                {% bootstrap_field form.options %}
            </div>
        {% endif %}

        {% if not element.pk %}
            {% bootstrap_field form.order %}
            <input type="hidden" name="prefix_id" value="{{ prefix_id }}" class="prefix_id">
        {% endif %}

        <button type="submit" class="btn btn-primary survey-element-save" title="{% trans 'Tallenna' %}">{% bootstrap_icon "ok" %} {% trans "Tallenna" %}</button>
        {% if element.pk %}
            <a href="{% url 'survey:question' survey_id=element.survey_id question_id=element.pk %}" class="btn btn-default ajaxy-link" data-ajaxy-target-method="replaceWith">
                {% trans "Peruuta" %}
            </a>
        {% endif %}

        <div class="btn-group pull-right">
            {% if not element.pk %}
                <button class="btn btn-default survey-element-up" title="{% trans 'Nosta' %}"><span class="glyphicon glyphicon-arrow-up"></span></button>
                <button class="btn btn-default survey-element-down" title="{% trans 'Laske' %}"><span class="glyphicon glyphicon-arrow-down"></span></button>
                <button class="btn btn-danger survey-element-delete" title="{% trans 'Poista' %}"><span class="glyphicon glyphicon-remove"></span></button>
            {% else %}
                {% include "survey/edit_mode/element_buttons.html" %}
            {% endif %}
        </div>
        <div class="clearfix"></div>
    </form>
</div>

<script type="text/javascript">
    $(function() {
        $('.survey-element-save').on('click', function() {
            $('html, body').animate({ scrollTop: $(this).parents('.survey-element').offset().top }, 500);
            console.log('executed scrollToElement');
            return true;
        });
    })
</script>

survey/templates/survey/edit_mode/subtitle.html
{% load i18n survey_tags bootstrap3 %}

<div class="survey-element survey-element-mode-edit survey-element-subtitle ajaxy-wrap {% if new %}survey-element-new{% endif %}">
    <form action="{{ request.path }}" class="ajaxy-form" method="post" data-ajaxy-target-method="replaceWith" novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}

        {% if not element.pk %}
            <input type="hidden" name="prefix_id" value="{{ prefix_id }}" class="prefix_id">
        {% endif %}

        <button type="submit" class="btn btn-primary survey-element-save" title="{% trans 'Tallenna' %}">{% bootstrap_icon "ok" %} {% trans "Tallenna" %}</button>
        {% if element.pk %}
            <a href="{% url 'survey:subtitle' survey_id=element.survey.pk subtitle_id=element.pk %}" class="btn btn-default ajaxy-link" data-ajaxy-target-method="replaceWith">
                {% trans "Peruuta" %}
            </a>
        {% endif %}

        <div class="btn-group pull-right">
            {% if not element.pk %}
                <button class="btn btn-default survey-element-up" title="{% trans 'Nosta' %}"><span class="glyphicon glyphicon-arrow-up"></span></button>
                <button class="btn btn-default survey-element-down" title="{% trans 'Laske' %}"><span class="glyphicon glyphicon-arrow-down"></span></button>
                <button class="btn btn-danger survey-element-delete" title="{% trans 'Poista' %}"><span class="glyphicon glyphicon-remove"></span></button>
            {% else %}
                {% include "survey/edit_mode/element_buttons.html" %}
            {% endif %}
        </div>
        <div class="clearfix"></div>
    </form>
</div>