conversation/urls.py
# coding: utf-8
from django.conf.urls import url
from libs.djcontrib.conf.urls import decorated_patterns
from libs.djcontrib.utils.decorators import obj_by_pk, combo
from libs.permitter.decorators import check_perm

from . import views
from .perms import CanVoteComment, CanRemoveComment, CanCommentConversation, \
    CanCancelVote, CanEditComment
from .models import Conversation, Comment, Vote

conv_by_pk = obj_by_pk(Conversation, 'conversation_id')
comment_by_pk = obj_by_pk(Comment, 'comment_id')


# Comments
urlpatterns = [
    url(r'^(?P<conversation_id>\d+)/kommentit/$', views.PreviewCommentsView.as_view(),
        name='comments_preview'),
    url(r'^(?P<conversation_id>\d+)/kommentti/(?P<comment_id>\d+)/$',
        views.CommentDetailView.as_view(template_name='comments/comment_detail.html'),
        name='comment_detail'),
    url(r'^(?P<conversation_id>\d+)/kommentti/(?P<comment_id>\d+)/lainaus/'
        r'(?P<quote_id>\d+)/$',
        views.CommentDetailView.as_view(template_name='comments/comment_detail.html'),
        name='comment_detail'),
    url(r'^(?P<conversation_id>\d+)/kommenttilohko/(?P<comment_id>\d+)/$',
        views.CommentDetailView.as_view(
            template_name='comments/comment_and_responses_block.html'),
        name='comment_detail_block'),
    url(r'^kommentti/(?P<comment_id>\d+)/poista/$',
        comment_by_pk(check_perm(CanRemoveComment)(views.RemoveCommentView.as_view())),
        name='remove_comment'),
    url(r'^kommentti/(?P<comment_id>\d+)/muokkaa/$',
        comment_by_pk(check_perm(CanEditComment)(views.EditCommentView.as_view())),
        name='edit_comment'),
    url(r'^(?P<comment_id>\d+)/peru/$',
        comment_by_pk(check_perm(CanCancelVote)(views.RemoveCommentVoteView.as_view())),
        name='cancel_vote'),
]

# Comments
urlpatterns += decorated_patterns(
    '', combo(conv_by_pk, check_perm(CanCommentConversation)),
    url(r'^(?P<conversation_id>\d+)/kommentoi/$', views.PostCommentView.as_view(),
        name='post_comment'),
    url(r'^(?P<conversation_id>\d+)/vastaa/(?P<comment_id>\d+)/$',
        views.PostResponseView.as_view(),
        name='post_response'),
)

# Votes
urlpatterns += decorated_patterns(
    '', combo(comment_by_pk, check_perm(CanVoteComment)),
    url(r'^(?P<comment_id>\d+)/kannata/$',
        views.VoteCommentView.as_view(choice=Vote.VOTE_UP), name='comment_vote_up'),
    url(r'^(?P<comment_id>\d+)/vastusta/$',
        views.VoteCommentView.as_view(choice=Vote.VOTE_DOWN), name='comment_vote_down')
)

help/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views
from .models import Instruction

link_slug_pattern = '{0}|{1}'.format(Instruction.TYPE_PRIVACY_POLICY,
                                     Instruction.TYPE_CONTACT_DETAILS)

urlpatterns = [
    url(r'^$', views.InstructionDetailFirst.as_view(permanent=True), name='instruction_list'),
    url(r'(?P<pk>\d+)/$', views.InstructionDetail.as_view(), name='instruction_detail'),
    url(r'^linkki/(?P<slug>%s)/$' % link_slug_pattern,
        views.LinkedInstructionRedirectView.as_view(permanent=True),
        name='linked_instruction_redirect'),
]

libs/attachtor/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url('^(?P<upload_group_id>[a-f0-9]{32})(?P<upload_token>[a-f0-9]{32})/$',
        views.UploadAttachmentView.as_view(),
        name='attachtor_file_upload')
)

otakantaa/urls.py
# coding=utf-8

from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.generic.base import RedirectView

from content.views import UploadAttachmentView, SchemesView

from libs.djcontrib.utils.decorators import combo
from libs.permitter.decorators import check_perm
from libs.moderation.helpers import auto_discover

from okmessages.views import FeedbackView

from .views import AllowedFileUploadExtensions, error_page_not_found
from .decorators import legacy_json_plaintext
from .perms import IsAuthenticated


auto_discover()

urlpatterns = [
    url('^api/$', RedirectView.as_view(url='/api/open/0.1/', permanent=False)),  # HACK
    url(r'^api/open/', include('openapi.urls', namespace='openapi')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', SchemesView.as_view(), name='schemes'),
    url(r'^kayttaja/', include('account.urls', namespace='account')),
    url(r'^', include('content.urls', namespace='content')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^hallinta/', include('okadmin.urls', namespace='okadmin')),
    url('^liitteet/laheta/(?P<upload_group_id>[a-f0-9]{32})'
        '(?P<upload_token>[a-f0-9]{32})/$',
        combo(check_perm(IsAuthenticated), legacy_json_plaintext)(
            UploadAttachmentView.as_view()
        ),
        name='attachtor_file_upload'),
    url('^liitteet/sallitut-paatteet/$', AllowedFileUploadExtensions.as_view(),
        name='allowed_file_upload_extensions'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^', include('survey.urls', namespace='survey')),
    url(r'keskustelut/', include('conversation.urls', namespace='conversation')),
    url(r'^suosikit/', include('favorite.urls', namespace='favorite')),
    url(r'^organisaatiot/', include('organization.urls', namespace='organization')),
    url(r'^palaute/$', FeedbackView.as_view(), name='feedback'),
    url(r'', include('okmoderation.urls', namespace='okmoderation')),
    url(r'^widget/', include('okwidget.urls', namespace='widget')),
    url(r'^tietoa-palvelusta/', include('help.urls', namespace='help')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.STATIC_URL.startswith('http'):
    urlpatterns += staticfiles_urlpatterns('/static/')

handler404 = error_page_not_found

conversation/models.py
# coding=utf-8

from __future__ import unicode_literals
from datetime import datetime

from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings
from django.db.models.query import QuerySet
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from actions.models import ActionGeneratingModelMixin
from content.models import ParticipationDetails


class Conversation(models.Model):
    def public_comments(self):
        return self.comments.public()

    def public_comments_filter_removed(self):
        return self.comments.public()

    def get_parent_scheme(self):
        return self.get_parent_participation().scheme

    def get_parent_participation(self):
        return ParticipationDetails.objects.get(
            content_type=ContentType.objects.get_for_model(Conversation),
            object_id=self.pk
        )

    def get_involved_user_ids(self):
        return self.comments.filter(user__isnull=False).values_list('user_id', flat=True)

    def last_participation_date(self):
        if self.comments.count():
            commented_on = self.comments.order_by('created').last().created.date()
            comments_pk_list = self.comments.all().values_list('pk', flat=True)
            last_vote = Vote.objects.filter(
                content_type=ContentType.objects.get_for_model(Comment),
                object_id__in=comments_pk_list
            ).order_by('created').last()
            if last_vote and last_vote.created.date() > commented_on:
                return last_vote.created.date()
            else:
                return commented_on
        return datetime.min.date()


COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 3000)


class CommentQuerySet(QuerySet):

    # excludes responses
    def comments(self):
        return self.filter(target_comment__isnull=True).public()

    def prefetch(self):
        return self.prefetch_related('user__settings')

    def public(self):
        # if self.count():
        #     scheme = self.first().conversation.get_parent_scheme()
        #     if scheme.premoderation is True:
        return self.filter(is_public=True)

    def filter_removed(self):
        # if self.count():
        #     scheme = self.first().conversation.get_parent_scheme()
        #     if scheme.premoderation is True:
        return self.filter(is_removed=False)

    def visible(self):
        return self.public().exclude(is_removed=True)


@python_2_unicode_compatible
class Comment(ActionGeneratingModelMixin, models.Model):

    conversation = models.ForeignKey(Conversation, related_name='comments', null=True)
    quote = models.ForeignKey('self', null=True, blank=True, related_name='quoted')
    target_comment = models.ForeignKey('self', null=True, blank=True,
                                       related_name='responses')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
                             related_name='comments')
    user_name = models.CharField(_("nimimerkki"), max_length=50, blank=True)
    title = models.CharField(_("otsikko"), max_length=255, blank=True)
    comment = models.TextField(_("kommentti"), max_length=COMMENT_MAX_LENGTH, default='')
    created = models.DateTimeField(default=timezone.now)
    ip_address = models.GenericIPAddressField(unpack_ipv4=True, blank=True, null=True)
    is_removed = models.BooleanField(default=False)
    removed_by = models.ForeignKey('account.User', blank=True, null=True)
    is_public = models.BooleanField(default=True)
    votes = GenericRelation('Vote', related_query_name='comments')
    admin_comment = models.BooleanField(default=False)
    objects = CommentQuerySet.as_manager()

    @cached_property
    def name(self):
        return self.user or self.user_name

    def is_anonymous(self):
        return self.user_id is None

    def is_response(self):
        return True if self.target_comment else False

    def voter_user_ids(self):
        return [x.voter.user_id for x in self.votes.all() if x.voter.user_id]

    def __str__(self):
        return "%s: %s..." % (self.name, self.comment[:50])

    def get_absolute_url(self):
        pk = self.target_comment.pk if self.is_response() else self.pk
        return reverse('conversation:comment_detail', kwargs={
            'conversation_id': self.conversation_id, 'comment_id': pk
        })

    # for moderation
    @property
    def owner_ids(self):
        return [self.user.pk] if self.user_id else []

    def action_kwargs_on_create(self):
        return {'actor': self.user}

    def fill_notification_recipients(self, action):
        self.conversation.get_parent_scheme().fill_notification_recipients(action)

    class Meta:
        ordering = ('created', )


class Voter(models.Model):
    VOTER_COOKIE = "joku"

    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, default=None)
    voter_id = models.CharField(max_length=32, unique=True)
    created = models.DateTimeField(default=timezone.now)


class VoteQuerySet(models.QuerySet):
    def up(self):
        return self.filter(choice=Vote.VOTE_UP)

    def down(self):
        return self.filter(choice=Vote.VOTE_DOWN)

    def balance(self):
        balance = sum([vote.choice for vote in self])
        return '+{}'.format(balance) if balance > 0 else balance

    def filter(self, *args, **kwargs):
        if 'content_object' in kwargs:
            content_object = kwargs.pop('content_object')
            content_type = ContentType.objects.get_for_model(content_object)
            kwargs.update({
                'content_type': content_type,
                'object_id': content_object.pk
            })
        return super(VoteQuerySet, self).filter(*args, **kwargs)


class Vote(models.Model):
    VOTE_UP = 1
    VOTE_DOWN = -1
    VOTE_NONE = 0

    voter = models.ForeignKey(Voter)
    client_identifier = models.ForeignKey('account.ClientIdentifier')

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    created = models.DateTimeField(auto_now_add=True)
    choice = models.SmallIntegerField()

    objects = VoteQuerySet.as_manager()

    @classmethod
    def votes_for(cls, model, instance=None):
        ct = ContentType.objects.get_for_model(model)
        kwargs = {'content_type': ct}
        if instance is not None:
            kwargs['object_id'] = instance.pk
        return cls.objects.filter(**kwargs)

    class Meta:
        unique_together = ('voter', 'content_type', 'object_id')

conversation/forms.py
# conding: utf-8

from __future__ import unicode_literals
from nocaptcha_recaptcha.fields import NoReCaptchaField
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _

from conversation.models import Comment


class BaseCommentForm(forms.ModelForm):
    quote = forms.IntegerField(widget=forms.HiddenInput, required=False)
    honeypot = forms.CharField(
        widget=forms.HiddenInput,
        required=False,
        label=_('If you enter anything in this field your comment will be treated as '
                'spam')
    )

    def clean_quote(self):
        quote_id = self.cleaned_data['quote']
        if quote_id:
            return get_object_or_404(Comment, pk=quote_id)
        return None

    def clean_honeypot(self):
        #Check that nothing's been entered into the honeypot.
        value = self.cleaned_data['honeypot']
        if value:
            raise forms.ValidationError(self.fields['honeypot'].label)
        return value


class BaseCommentFormAnon(BaseCommentForm):
    captcha = NoReCaptchaField(label=_("Tarkistuskoodi"))

    def __init__(self, *args, **kwargs):
        super(BaseCommentFormAnon, self).__init__(*args, **kwargs)
        self.fields['user_name'].required = True


class CommentFormTitleRequiredMixin(object):
    def __init__(self, *args, **kwargs):
        super(CommentFormTitleRequiredMixin, self).__init__(*args, **kwargs)
        self.fields['title'].required = True


class CommentForm(CommentFormTitleRequiredMixin, BaseCommentForm):
    class Meta:
        model = Comment
        fields = ('title', 'comment', )


class CommentFormAnon(CommentFormTitleRequiredMixin, BaseCommentFormAnon):
    class Meta:
        model = Comment
        fields = ('user_name', 'title', 'comment', )


class CommentResponseForm(BaseCommentForm):
    class Meta:
        model = Comment
        fields = ('quote', 'comment', )
        labels = {'comment': _("Vastaus")}


class CommentResponseFormAnon(BaseCommentFormAnon):
    class Meta:
        model = Comment
        fields = ('user_name', 'quote', 'comment', )
        labels = {'comment': _("Vastaus")}


class EditCommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditCommentForm, self).__init__(*args, **kwargs)
        if self.instance.is_response():
            self.fields['comment'].label = _("Vastaus")

    class Meta:
        model = Comment
        fields = ('comment', )


class DeleteCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ()

conversation/templates/comments/comment_and_responses_block.html
{% load i18n comments fontawesome %}

<a class="btn btn-default" href="{% url 'content:participation:conversation_detail' scheme_id=request.participation_detail.scheme.pk participation_detail_id=request.participation_detail.pk %}">{% trans "Katso muut kommentit" %}</a>

{% if object.conversation in perm.conversation.CanCommentConversation %}
    <a class="btn btn-primary pull-right" href="#uusi-kommentti">{% fa_icon "comment" alt=_("Puhekupla") %} {% trans "Vastaa" %}</a>
    <div class="clearfix"></div>
{% endif %}

{% include 'comments/comment_item_comment_detail.html' %}

{% for response in object.responses.public.all %}
    {% include 'comments/comment_response_item.html' with comment=response response_link='#uusi-kommentti' %}
{% endfor %}

<hr>

{% if object.conversation in perm.conversation.CanCommentConversation %}
    {% get_comment_form 'form' get_response_form=True %}
    {% include 'comments/comment_response_form.html' with comment=object %}
{% endif %}

<script type="text/javascript">
    $(function() {
        $('blockquote').expander();
    });
</script>

conversation/templates/comments/comment_confirm_delete.html
{% extends 'otakantaa/inline_edit_base_form.html' %}
{% load i18n static %}

{% block before_form %}
    <div class="well remove-comment-block">
        <h3>{% trans "Kommentin poisto" %}</h3>
        <p>{% trans "Poistetaanko kommentti varmasti?" %}</p>
{% endblock before_form %}

{% block form_actions %}
    <input type="submit" class="btn btn-primary" value="{% trans "Poista" %}" />
    <button class="btn btn-default cancel-remove-comment" title="{% trans "Peruuta poistaminen" %}">{% trans "Peruuta" %}</button>
{% endblock form_actions %}

{% block after_form %}
    </div>
    <script type="text/javascript">
        $(function() {
            $('.cancel-remove-comment').on('click', function() {
                $('.remove-comment-block').remove();
            });
        });
    </script>
{% endblock after_form %}

conversation/templates/comments/comment_detail.html
{% extends 'participation/conversation_detail.html' %}
{% load i18n %}

{% block content_subcontent %}
    <div id="comments">
        {% include 'comments/comment_and_responses_block.html' %}
    </div>
{% endblock content_subcontent %}

conversation/templates/comments/comment_form.html
{% load i18n static bootstrap3 %}

<div class="ajaxy-wrap">

    <a name="uusi-kommentti"></a>
    <h4>{% trans "Lisää uusi Kommentti" %}</h4>
    {% include 'comments/premoderation_message.html' %}

    <form class="ajaxy-form" novalidate action="{% url 'conversation:post_comment' conversation_id=conversation.pk %}" method="post" data-ajaxy-success-target="#comments">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="submit" class="btn btn-primary" value="{% trans 'Lähetä kommentti' %}">
    </form>
</div>

conversation/templates/comments/comment_item.html
{% extends 'comments/comment_item_base.html' %}
{% load i18n %}

{% block response_link %}
    {% if conversation in perm.conversation.CanCommentConversation %}
        <a href="{% url 'conversation:comment_detail' conversation_id=conversation.pk comment_id=comment.pk %}#uusi-kommentti">{% trans "Vastaa" %}</a> <span>({{ comment.responses.public.count }})</span>
    {% endif %}
{% endblock response_link %}

conversation/templates/comments/comment_item_base.html
{% load i18n fontawesome otakantaa_tags flagging moderation %}

<article class="ajaxy-wrap {% block article_class %}comment{% endblock article_class %}">
    <a name="kommentti-{{ comment.pk }}"></a>

    {% if comment.is_removed %}
        {% include 'comments/comment_item_removed.html' %}
    {% else %}
        <header>
            {% if comment.title %}
                <h3><a href="{{ comment.get_absolute_url }}">{{ comment.title }}</a></h3>
            {% endif %}

            <div class="pull-left">
                {% include 'account/profile_picture.html' with class='profile-pic-small' user=comment.user highlight=comment.admin_comment %}
            </div>
            <div class="pull-left comment-info">
                <p><span class="comment-name{% if comment.admin_comment %} username-highlight{% endif %}">{{ comment.name }}</span><br>{{ comment.created }}</p>
            </div>
            {% block voting %}
                <div class="pull-right thumbs ajaxy-wrap">
                    {% include 'comments/comment_voting.html' %}
                </div>
            {% endblock voting %}
            <div class="clearfix"></div>
        </header>
        <div class="comment-content">

            {% block quote %} {% endblock quote %}

            <div id="comment-text-{{ comment.pk }}" class="ajaxy-wrap">{% include 'comments/comment_text.html' %}</div>

            {% block attachments %} {% endblock attachments %}
            <div id="remove-comment-container-{{ comment.pk }}"></div>
            <footer>
                {% block response_link %} {% endblock response_link %}
                {% block footer_tools %}
                    <div class="pull-right">
                        {% if comment in perm.conversation.CanRemoveComment %}
                            <a href="{% url 'conversation:remove_comment' comment.pk %}" class="ajaxy-link" data-ajaxy-target="#remove-comment-container-{{ comment.pk }}" title="{% trans "Poista kommentti" %}">{% fa_icon "remove" alt=_("Poista") %} {% trans "Poista" %}</a> |
                        {% endif %}
                        {% if comment in perm.conversation.CanRemoveComment %}
                            <a href="{% url 'conversation:edit_comment' comment.pk %}" class="ajaxy-link" data-ajaxy-target="#comment-text-{{ comment.pk }}" title="{% trans "Muokkaa kommenttia" %}">{% fa_icon "edit" alt=_("Muokkaa") %} {% trans "Muokkaa" %}</a> |
                        {% endif %}
                        <span>{% if not comment.is_removed %}{% flag_link comment label=_("Ilmianna") %}{% endif %}</span>
                        {% if request.participation_detail.scheme.is_public %}
                            |
                            {% with url=BASE_URL|add:comment.get_absolute_url %}
                                <div class="display-inline" style="margin-left:2px;">{% include 'otakantaa/share_link.html' with anchor='#kommentti-'|add_to_str:comment.pk|urlencode noicon=True object=comment url=url %}</div>
                            {% endwith %}
                        {% endif %}
                    </div>
                {% endblock footer_tools %}
                <div class="clearfix"></div>
            </footer>
        </div>
    {% endif %}
</article>

conversation/templates/comments/comment_item_comment_detail.html
{% extends 'comments/comment_item_base.html' %}
{% load i18n %}

{% block response_link %}
    {% if comment.conversation in perm.conversation.CanCommentConversation %}
        <a href="#uusi-kommentti">{% trans "Vastaa" %}</a> <span>({{ comment.responses.public.count }})</span>
    {% endif %}
{% endblock response_link %}

conversation/templates/comments/comment_item_moderation.html
{% extends 'comments/comment_item_base.html' %}
{% load i18n %}

{% block voting %}{% endblock voting %}
{% block footer_tools %}{% endblock footer_tools %}

conversation/templates/comments/comment_moderation.html
{% load i18n bleach_tags %}

{% with comment=object %}
    {% include 'comments/comment_item_moderation.html' with comment=comment %}
{% endwith %}

conversation/templates/comments/comment_response_form.html
{% load i18n static bootstrap3 %}

<div class="ajaxy-wrap">

    <a name="uusi-kommentti"></a>
    <h4>{% trans "Vastaa" %}</h4>
    {% include 'comments/premoderation_message.html' %}

    <form id="comment-response-form" class="ajaxy-form" novalidate action="{% url 'conversation:post_response' conversation_id=comment.conversation.pk comment_id=comment.pk %}" method="post" data-ajaxy-success-target="#comments">
        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="submit" name="submit" class="btn btn-primary" value="{% trans 'Lähetä vastaus' %}">
    </form>
</div>

<script type="text/javascript">
    $(function() {

        var addQuote = function(triggerer) {
            $('#id_quote').val(triggerer.attr('data-quote-id'));

            var text = triggerer.parents('div.comment-content').find('.comment-text').html();
            var name = triggerer.parents('article').find('.comment-name').html();

            if (triggerer.parents('div.comment-content').find('textarea').length) {
                text = triggerer.parents('div.comment-content').find('textarea').val()
                console.log('textarea');
            }

            var quote = $('<blockquote/>', {
                html: '<strong>' + name + ' kirjoitti:</strong><br>' + text
            });
            quote.expander({slicePoint: 100});
            quote.insertAfter('#id_quote');
        };

        var removeQuote = function() {
            $('#id_quote').val('');
            var quote = $('#comment-response-form').find('blockquote');
            if (quote !== undefined) {
                quote.remove();
            }
        };

        $(document).on('click', 'a[href="#uusi-kommentti"]', function() {
            removeQuote();
            if ($(this).hasClass('response-quote')) {
                addQuote($(this));
            }
        });

        var quote_pk = '{{ request.resolver_match.kwargs.quote_id }}';

        if (quote_pk) {
            $('.response-quote[data-quote-id="'+quote_pk+'"]').trigger('click');
        }
    });
</script>

conversation/templates/comments/comment_response_item.html
{% extends 'comments/comment_item_base.html' %}
{% load i18n moderation %}

{% block article_class %}response{% endblock article_class %}

{% block quote %}
    {% if comment.quote %}
        {% if comment.quote.is_removed %}
            <blockquote class="quote-target-removed">{% trans "Lainattu vastaus on poistettu." %}</blockquote>
        {% else %}
            <blockquote><strong>{{ comment.quote.name }} {% trans "kirjoitti" %}:</strong> <br>
            {% include 'comments/comment_text.html' with comment=comment.quote %}
            </blockquote>
        {% endif %}
    {% endif %}
{% endblock quote %}

{% block response_link %}
    {% if comment.conversation in perm.conversation.CanCommentConversation %}
        <a href="{{ response_link }}" class="response-quote" data-quote-id="{{ comment.pk }}">{% trans "Vastaa lainaten" %}</a>
    {% endif %}
{% endblock response_link %}

conversation/templates/comments/comment_voting.html
{% load i18n fontawesome comments %}

{% get_vote_icon comment 'up' %}
{% get_vote_icon comment 'down' %}
{% get_voting_disabled_class comment %}

{% if request.user.is_authenticated and comment in perm.conversation.CanCancelVote %}
    <a href="{% url 'conversation:cancel_vote' comment.pk %}" class="ajaxy-link" data-ajaxy-method="post">{% trans "Peru kannanotto" %}</a>
{% endif %}
<div class="btn-group" role="group">
    <a href="{% url 'conversation:comment_vote_up' comment.pk %}" data-ajaxy-method="post" class="btn btn-default ajaxy-link{{ disabled_class }}">{% fa_icon icon_thumb_up alt=_("Peukku ylös") %} {{ comment.votes.up.count }}</a>
    <a href="{% url 'conversation:comment_vote_down' comment.pk %}" data-ajaxy-method="post" class="btn btn-default ajaxy-link{{ disabled_class }}">{% fa_icon icon_thumb_down alt=_("Peukku alas") %} {{ comment.votes.down.count }}</a>
</div>
<span class="thumbs-counter{% if comment.votes.balance < 0 %} negative{% endif %}">{{ comment.votes.balance }}</span>

conversation/templates/comments/comments_preview.html
{% load i18n fontawesome comments %}

{% if conversation in perm.conversation.CanCommentConversation %}
    <a class="btn btn-primary" href="#uusi-kommentti">{% fa_icon "comment" alt=_("Puhekupla") %} {% trans "Uusi kommentti" %}</a>
{% endif %}

{% for comment in conversation.comments.comments.prefetch.all %}
    {% include 'comments/comment_item.html' %}
    {% if comment.responses.public.count %}
        {% url 'conversation:comment_detail' conversation_id=conversation.pk comment_id=comment.pk quote_id=comment.responses.last.pk as link_url %}
        {% include 'comments/comment_response_item.html' with comment=comment.responses.public.last response_link=link_url|add:"#uusi-kommentti" %}
    {% endif %}
    {% if comment.responses.public.count >= 2 %}
        <a href="{% url 'conversation:comment_detail' conversation_id=conversation.pk comment_id=comment.pk %}">{% trans "Näytä lisää vastauksia" %}</a>
    {% endif %}
    {% if not forloop.last %}
        <hr>
    {% endif %}
{% endfor %}

<div class="margin-top-2 clearfix"></div>

<hr>

{% if conversation in perm.conversation.CanCommentConversation %}
    {% get_comment_form 'form' %}
    {% include 'comments/comment_form.html' %}
{% endif %}

<script type="text/javascript">
    $(function() {
        $('blockquote').expander();
    });
</script>

conversation/templates/comments/premoderation_message.html
{% load i18n bootstrap3 %}

{% if request.is_ajax %}{# HACK: dont re-display non-ajax messsages already show on page header #}
    {% bootstrap_messages %}
{% endif %}

{% if request.participation_detail.scheme.premoderation %}
    <div class="alert alert-warning">{% trans "Kommenttien ja vastausten esimoderointi on käytössä. Uudet kommentit ja vastaukset julkaistaan vasta kun palvelun moderaattori on hyväksynyt ne." %}</div>
{% endif %}